### ISSUE TITLE
Question about `adobe::capture_allocator`.

### ISSUE THREAD

**Issue by gdianaty** [stlab/adobe_source_libraries#104]
Hello!

When exploring the use of `adobe::capture_allocator`, I ran into an edge-case.

When creating a vector as such:

```cpp
// An example object, who's only notable trait is the use of new/delete.
struct BoundryTest_t
{
	BoundryTest_t()
	{
		p = new char[128];
	}

	~BoundryTest_t()
	{
		delete p;
	}

	char* p = NULLPTR;
};

// This function exists in another DLL (bar.dll), not the current DLL (foo.dll).
// Simply calls push_back with default constructor arguments a few times.
void MyFunction(std::vector<BoundryTest_t, adobe::capture_allocator<BoundryTest_t>>& vecTestObjects);
```

If I'm understanding this correctly - due to the object `BoundryTest_t` invoking `new` within the constructor, this causes a memory leak. When MyFunction in foo.dll allocates new instances of BoundryTestVec_t and the constructor is invoked, the `construct_at` function is run inside the bar.dll. This results in heap corruption in the current foo.dll scope upon the occasion of foo.dll attempting to clean up the vector.

What is the expected workaround for this behavior?

Thank you for your time!

**Comment by gdianaty** [comment]
Some more ideas to fix this:
- Thread-local captive allocator `CaptiveAllocators_t*`. Before construct_at and deconstruct_at are run, the thread-local captive allocator pointer is set to specifically allow for these edge cases. This implies that users of Threshold are aware of this and obey it when writing constructors.
- Mandatory first-operand of all ThCaptiveAllocator `T` to be `CaptiveAllocators_t*` for use by captive allocators. SFINAE would prevent this from being catastrophic.

**Comment by sean-parent** [comment]
The capture allocator is not transitive. It is intended for APIs that are carefully constructed to be ABI resilient, even its use in `std::vector<>` does not provide any guarantees because `std::vector<>` makes no ABI guarantees. ASL used to have [a number of ABI stable types](https://stlab.adobe.com/group__abi__safe.html) but I removed them several years ago because in every use case I could find, they were misused or mixed with non-ABI stable types defeating the purpose. I could not see value in maintaining them.

For your problem above - if you have multiple DLL's with different implementations of new/delete (through overrides or standard library versions) you have an ODR violation. The capture_allocator may be a tool to work around the issue if for some reason you must support this environment, but all types passed across your API boundary to your DLL, and any inlined functions, must be ABI resilient. An inlined new/delete is not because new/delete are replaceable operations.

**Comment by gdianaty** [comment]
Thank you!
